# from https://github.com/Parallels/atlassian-restrict-branch-model/blob/master/.travis.yml
sudo: false

language: java

branches:
  except:
  - /^v[0-9]*/

before_install:
- wget https://marketplace.atlassian.com/download/plugins/atlassian-plugin-sdk-tgz
- mkdir opt
- tar -xvzf *plugin-sdk* -C opt
- mv opt/*plugin-sdk* opt/atlassian-plugin-sdk
- chmod a+x opt/atlassian-plugin-sdk/bin/*
- chmod a+x opt/atlassian-plugin-sdk/apache-maven-*/bin/*
- export PATH=opt/atlassian-plugin-sdk/bin:opt/atlassian-plugin-sdk/apache-maven-*/bin:$PATH
- atlas-version
install:
- atlas-mvn install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true
script:
- atlas-mvn package -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

after_success:
# CREATE GIT TAG
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=v$TRAVIS_BUILD_NUMBER
- echo -n $GIT_TAG > VERSION
- git commit -m "Set build VERSION number" VERSION
- git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
- git push --quiet https://$GITHUBKEY@github.com/ls1intum/bamboo-server-notification-plugin $GIT_TAG > /dev/null 2>&1

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "Pc9pqXypXV1/zViIzWD4q3UQ5/AyauDhAPHcSEMEedJujidSKlDfFVoOGC7P7nxUv8Cvliz0+eq3T9ilIeQK0vYKwuBkOEujyRXRKWo7eDuJ12DPHQTEPK+++5pz8wivvAdAru/vinygO0BUpzEKo63tBRXEWqQSMv4EQoWxGukcYN92+NAqJHZdyQ8nc8TwN9zWdeIW1XC2H2R2jddz8hMvhfbdC9MT4VByE/gHtYTZxQeIWJ+bJsxXfCjAXwMnfzLVqp/Nd5rYMnU0tVM93Mwx7LWrs26w7PI9RHIBRUePn70a50q9QelMo81zVUJ6qDpn2jlES/4D92HH/3FzCxxJ3ZSnoedxBT7X5+dFM6tGT0ImmXahubgnHLYd7XEOWQSar5+l3x/YVHy0ElcfXZpTfXdq6338rb/4EFyF1Rla+mc1RGet15RPca50khH4Br5bD1HBUMp72pxg0498xrn+RcjspLkWUjnQi4gFr96GX5qiQj+3ZacTgILEQiBa/2dNg4KuLONXb7eh72ueY9yQC7cU2PgNvkMXXC8TJ5vToLk/G/r0fqB8+JVMmCH9lbcTBy3xnkzBUZL3ZlpIUfHUk1N5tNtq2s8T6+R6Wu43X2KsFR9KzFIMr0TQ+KAYCF15LzEO9uB2Il2p4OvIz5M6F7mQIgOAklCIG5E83RM="
  file:
  - target/*.jar
  file_glob: true
  on:
    branch: master